# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(493, 658)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.songListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.songListWidget.setObjectName("songListWidget")
        self.horizontalLayout_1.addWidget(self.songListWidget)
        self.loadButton = QtWidgets.QPushButton(self.centralwidget)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout_1.addWidget(self.loadButton)
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.playSongButton = QtWidgets.QPushButton(self.centralwidget)
        self.playSongButton.setObjectName("playSongButton")
        self.horizontalLayout_2.addWidget(self.playSongButton)
        self.pauseSongButton = QtWidgets.QPushButton(self.centralwidget)
        self.pauseSongButton.setObjectName("pauseSongButton")
        self.horizontalLayout_2.addWidget(self.pauseSongButton)
        self.stopSongButton = QtWidgets.QPushButton(self.centralwidget)
        self.stopSongButton.setObjectName("stopSongButton")
        self.horizontalLayout_2.addWidget(self.stopSongButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.tabLayout1 = QtWidgets.QGridLayout()
        self.tabLayout1.setObjectName("tabLayout1")
        self.tabLayout1Label = QtWidgets.QLabel(self.tab)
        self.tabLayout1Label.setAlignment(QtCore.Qt.AlignCenter)
        self.tabLayout1Label.setObjectName("tabLayout1Label")
        self.tabLayout1.addWidget(self.tabLayout1Label, 0, 0, 1, 1)
        self.tablLayout1TableWidget = QtWidgets.QTableWidget(self.tab)
        self.tablLayout1TableWidget.setObjectName("tablLayout1TableWidget")
        self.tablLayout1TableWidget.setColumnCount(0)
        self.tablLayout1TableWidget.setRowCount(0)
        self.tabLayout1.addWidget(self.tablLayout1TableWidget, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.tabLayout1, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabLayout2 = QtWidgets.QGridLayout()
        self.tabLayout2.setObjectName("tabLayout2")
        self.gridLayout_4.addLayout(self.tabLayout2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 493, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadButton.setText(_translate("MainWindow", "Load File(s)..."))
        self.playSongButton.setText(_translate("MainWindow", "Play"))
        self.pauseSongButton.setText(_translate("MainWindow", "Pause"))
        self.stopSongButton.setText(_translate("MainWindow", "Stop"))
        self.tabLayout1Label.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))

